#!/bin/bash

HISTSIZE=1000
HISTFILESIZE=2000
HISTCONTROL=ignorebot

parse_git_branch() {
    git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/(\1)/'
}

# https://wiki.archlinux.org/title/Bash/Prompt_customization
# \A                            = Current time
# \[\033[01;34m\]\w\[\033[00m\] = Current directory
# \[\e[00m\]                    = Reset color
PS1='\A \[\033[01;34m\]\w\[\033[00m\] \[\e[91m\]$(parse_git_branch) \[\e[00m\]'

if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    alias dir='dir --color=auto'
    alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi